### ISSUE TITLE
expected IF token at start of conditional, but got IDENTIFIER

### ISSUE THREAD

**Issue by 360disrupt** [decaffeinate/coffee-lex#175]
decaffeinate is crashing on my CoffeeScript input:

```coffee
self = @

if process.env.INSTANCE_TYPE == 'abc'
  instanceType = 'abc'
else
  console.log "abc"

```

[REPL](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=self%20%3D%20%40%0A%0Aif%20process.env.INSTANCE_TYPE%20%3D%3D%20'abc'%0A%20%20instanceType%20%3D%20'abc'%0Aelse%0A%20%20console.log%20%22abc%22%0A)

I get this error:

```
expected IF token at start of conditional, but got IDENTIFIER
```
-->

This is solved by placing the `self = @` below the `if/else`

Related to:
https://github.com/decaffeinate/decaffeinate/issues/275
https://github.com/decaffeinate/decaffeinate/issues/306

**Comment by eventualbuddha** [comment]
This is an issue with coffee-lex, as it is lexing this code incorrectly. Here's a minimal [example](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=coffee-lex&code=a%20%3D%20%40%0Aif%20b%20then%20c):

```coffee
a = @
if b then c
```

It's lexing the `if` as an `IDENTIFIER` rather than an `IF`. I assume that's because the newline after the `@` isn't resetting the lex state and it's interpreting it like `@if`.
