### ISSUE TITLE
multi line double/single quoted strings conversion issue.

### ISSUE THREAD

**Issue by iainb** [decaffeinate/coffee-lex#6]
This issue was observed while using decaffeinate and I think the problem might be easier to fix with a bit of help from coffee-lex, though perhaps I'm wrong.

example code that causes decaffeinate to crash:

``` coffeescript
x = "double quoted
     multi line string"
```

becomes the following when converted to js

``` js
var x;

x = "doube quoted multi line string";
```

Currently decaffeinate fails to convert this correctly, iirc from my debugging its leaving the new line in the middle of the multi line string, which is invalid es6 code.

I looked into fixing this into decaffeinate and I'm not sure if the tokens produced by coffee-lex are correct (or perhaps it is correct but it could produce different tokens that are more useful?).

This is probably best demonstrated by a test that currently passes.

``` es6
  it('handles double quoted multi line strings', () =>
    deepEqual(
      lex(`"doube quoted multi\n     line string"`).toArray(),
      [
        new SourceToken(DSTRING, 0, 37)
      ]
    )
  );
```

Should the coffee-lex actually be producing multiple tokens e.g STRING_START, STRING_CONTENTS, STRING_CONTENTS, STRING_END. Or something similar? It feels that something similar would be easier to work with in decaffeinate.

**Comment by eventualbuddha** [comment]
Yes, turning such a string into a series of `STRING_START`, `STRING_CONTENT`, `STRING_END` would be more appropriate.

**Comment by alangpierce** [comment]
Agreed that reworking coffee-lex's approach in this case would be nice, and may help simplify all of this code. The referenced issue ( https://github.com/decaffeinate/decaffeinate/issues/220 ) is fixed now, but other issues like https://github.com/decaffeinate/decaffeinate/issues/554 still exist. I'll close this issue in favor of the open decaffeinate issues; since the projects are so inter-related, it seems best to use the top-level decaffeinate project for the list of bugs, even when a fix might be in decaffeinate-parser or coffee-lex (or in some combination of the three projects or other projects).
